# Generated by Django 3.2 on 2022-10-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('US_corn_grain_yield', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
