# Generated by Django 3.2 on 2022-10-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('station_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('max_temp', models.FloatField(default=-9999)),
                ('min_temp', models.FloatField(default=-9999)),
                ('precipitation', models.FloatField(default=-9999)),
            ],
            options={
                'unique_together': {('station_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('station_id', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('avg_max_temp', models.FloatField(null=True)),
                ('avg_min_temp', models.FloatField(null=True)),
                ('total_precipitation', models.FloatField(null=True)),
            ],
            options={
                'unique_together': {('station_id', 'year')},
            },
        ),
    ]
